[package]
name = "panetiere-mobile-tools"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anymone-bench = { path = "../../crates/anymone-bench" }
panetiere = { git = "https://github.com/flashbots/panetiere", rev = "dc01b293e0d41a4869739af8b685853ac2c7970c" }

[[bin]]
name = "panetiere-mobile-bench"
path = "src/bin/panetiere-mobile-bench.rs"

[[bin]]
name = "panetiere-mobile-merge"
path = "src/bin/panetiere-mobile-merge.rs"
