[package]
name = "panetiere-mobile-tools"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anymone-bench = { path = "../../crates/anymone-bench" }
panetiere = { git = "https://github.com/flashbots/panetiere", rev = "e994fd9a00d0f7f81d72a169b876bbc792690667" }

[[bin]]
name = "panetiere-mobile-bench"
path = "src/bin/panetiere-mobile-bench.rs"

[[bin]]
name = "panetiere-mobile-merge"
path = "src/bin/panetiere-mobile-merge.rs"
