[package]
name = "anymone-bench"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "anymone_bench"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
anymone-core = { git = "ssh://git@github.com/flashbots/anymone", rev = "0913395cefba21ae55b319471b5778462e9e48f7" }
libc = "0.2"
once_cell = "1"
panetiere = { git = "https://github.com/flashbots/panetiere", rev = "dc01b293e0d41a4869739af8b685853ac2c7970c" }
rand_chacha = "0.3"
rayon = "1"
thiserror = "1"
uniffi = "0.29"
